### ISSUE TITLE
Return 404 instead of 400/500 on cache miss?

### ISSUE THREAD

**Issue by xi-ao** [danslo/magento2-module-automatic-persisted-queries#11]
Hi,

I'm not sure but my understanding of the [Apollo documentation](https://www.apollographql.com/docs/react/api/link/persisted-queries) is not to return a 400 on GET and 500 on POST when the query is not found. Moreover, in a strict HTTP compliant exchange, "something not found" would clearly be a 404.

The issue here is that monitoring tools interpret a 500 return code as a critical error that should be investigated, while here it's just a normal situation that happens in normal operation. This leads to a pollution of the monitoring tool and alerts being sent much too often for no good reasons.

As from the Wikipedia page:

> 400 Bad Request
> The server cannot or will not process the request due to an apparent client error (e.g., malformed request syntax, size too large, invalid request message framing, or deceptive request routing).

That doesn't seem to be the case here. The client is not at fault, it's just asking for a resource that cannot be found and has no way to know if it's available or not beforehand.

> 500 Internal Server Error
> A generic error message, given when an unexpected condition was encountered and no more specific message is suitable.

Well, that's not the server's fault either. The resource simply does not exist.

> 404 Not Found
> The requested resource could not be found but may be available in the future. Subsequent requests by the client are permissible.

That seems perfectly suited to our situation.

What do you think?

**Comment by danslo** [comment]
Hi!

We've noticed that the Apollo docs do not always match the implementation... (another [example](https://github.com/danslo/magento2-module-automatic-persisted-queries/issues/6)).

While developing, I checked the response codes from apollo-server and inherited those as to maintain compatibility with apollo-client (or any other client that was built against apollo-server). See also:
https://github.com/danslo/magento2-module-automatic-persisted-queries/blob/main/Plugin/PersistedQueryPlugin.php#L88

Has that situation changed?

**Comment by xi-ao** [comment]
I'm not in charge of the apollo-client on the project, only of the Magento backend, but I've talked with the developers and apparently the most important is the return code <> 200 and the PERSISTED_QUERY_NOT_FOUND code in the body. The HTTP code does not seem to be relevant for the processing.

**Comment by danslo** [comment]
What I am trying to say is that I place more value on producing the exact same behavior as apollo-server, than I do being 100% compliant with stricter standards. If upstream changes their status codes, I am happy to change them here as well :)

Maybe a good common ground is to allow the status code to be configured via a config setting, but leaving the default behavior to match apollo.

**Comment by xi-ao** [comment]
> Maybe a good common ground is to allow the status code to be configured via a config setting, but leaving the default behavior to match apollo.

That would be perfect. :ok_hand: 
Otherwise we'll have to use a composer-patch to fix this faulty behavior on our side, but I doubt we're the only ones interested in a long-term solution.

**Comment by danslo** [comment]
Closed via https://github.com/danslo/magento2-module-automatic-persisted-queries/pull/12.
