### ISSUE TITLE
apollo persistent link is not working as expected

### ISSUE THREAD

**Issue by fooman** [danslo/magento2-module-automatic-persisted-queries#6]
I am currently trialling this with PWA studio with using `@apollo/client/link/persisted-queries`
https://www.apollographql.com/docs/react/api/link/persisted-queries/

Contrary to the documentation here
![image](https://user-images.githubusercontent.com/455508/119910106-82848300-bfaa-11eb-8b0a-218498ba623b.png)

in my trials the client on the missed hash response does resend the query but never includes the hash. Not sure if this is an outdated graphic or something undocumented in the apollo client.

Currently simply having the server always create the hash seems to work better

```
    public function afterDispatch(
        GraphQl $subject,
        ResponseInterface $result,
        RequestInterface $request
    ): ResponseInterface {
        $data = $this->getDataFromRequest($request);

        if (!isset($data['query'])) {
            return $result;
        }

        $cacheKey = $this->getCacheKeyFromQueryHash(hash('sha256', $data['query']));
        if ($this->cache->load($cacheKey) === false) {
            $this->cache->save($data['query'], $cacheKey, [Apq::CACHE_TAG]);
        }

        return $result;
    }
```   

Keen to hear if you are seeing something different.

**Comment by danslo** [comment]
Interesting. I will admit that I have only run Apollo server, and fired custom requests at it using curl to check the correct responses/headers/etc. I didn't actually use `@apollo/client/link/persisted-queries` myself. 

Not only that image shows that it sends both query and hash, [Persisted Queries Link docs](https://www.apollographql.com/docs/react/api/link/persisted-queries/) do so as well:
>Client sends both hash and query string to Server

Do you happen to have a minimal testcase that uses `@apollo/client/link/persisted-queries` that I could try? (maybe with the [most basic query](https://github.com/danslo/magento2-module-automatic-persisted-queries/blob/main/Test/Integration/PersistedQueryTest.php#L22) there is). Preferably something I can use straight from the CLI with node.

If not that's cool, and I'll look at recreating the issue myself.

**Comment by fooman** [comment]
@danslo I have tried to create this
https://ggkjf.csb.app/
source here
https://codesandbox.io/s/apollo-persisted-query-no-retry-ggkjf

it's not working 100% but shows that even though the graphql back-end responds with a 500 on a post request no automatic retry is sent.

I wasn't able to actually get the proper response (probably due to some CORS issue) but am hoping it's a small enough testcase that you can point at your back-end.

**Comment by fooman** [comment]
Hmm the reproducer against the Magento back-end should never work as the error does not include PersistedQueryNotFound https://github.com/apollographql/apollo-client/commit/402905367dfb299ee714e5150077bd9c85d0ab10#diff-9cb38b9552043cac84bbba5a146950eeb8a7a2e4226cf26d80b4972f48d7c911R147

**Comment by danslo** [comment]
It [should](https://github.com/danslo/magento2-module-automatic-persisted-queries/blob/d54e5887ba0fb91d03acf64e9eb06c74558018d4/Plugin/PersistedQueryPlugin.php#L91) return that error though.

It's late here, I will have a look tomorrow, thanks for the testcase :)

**Comment by fooman** [comment]
@danslo the url in the testcase was just using Adobe's public PWA studio back-end which does not have your extension.  I have just made an update which should now make this easier to work with.

In `packages.json` adjust the proxy to your back-end. Then run `npm start`.

With a cleared back-end cache I am getting the following sequence when opening [localhost:3000](http://localhost:3000):

```
curl 'http://localhost:3000/graphql?variables=%7B%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%22a4e6b136e29639be9263bdd13d6d0c2fdf50473ff85055f5cefd3737c51d1586%22%7D%7D' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"' \
  -H 'accept: */*' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:3000/' \
  -H 'Accept-Language: en-GB,en;q=0.9,en-US;q=0.8,de;q=0.7,sv;q=0.6' \
  -H 'Cookie: private_content_version=5d93d8a8542cb2acdbf225695d516678' \
  --compressed
```
```
{"errors":[{"message":"PersistedQueryNotFound","extensions":{"code":"PERSISTED_QUERY_NOT_FOUND"}}]}
```

Then the retry but without hash
```
curl 'http://localhost:3000/graphql' \
  -H 'Connection: keep-alive' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"' \
  -H 'accept: */*' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'Origin: http://localhost:3000' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:3000/' \
  -H 'Accept-Language: en-GB,en;q=0.9,en-US;q=0.8,de;q=0.7,sv;q=0.6' \
  -H 'Cookie: private_content_version=5d93d8a8542cb2acdbf225695d516678' \
  --data-raw '{"variables":{},"query":"{\n  urlResolver(url: \"/\") {\n    id\n    relative_url\n    redirectCode\n    type\n    __typename\n  }\n}\n"}' \
  --compressed
  ```
  
  ```
  {"data":{"urlResolver":{"id":8,"relative_url":"home","redirectCode":0,"type":"CMS_PAGE","__typename":"EntityUrl"}}}
  ```

**Comment by fooman** [comment]
And the more I look at https://github.com/apollographql/apollo-client/blob/18b439e1b151f1e41385ff5cd3186a230cefee4c/src/link/persisted-queries/index.ts#L169 the more I think the client has no chance of ever sending the hash alongside the full query. supportsPersistedQueries gets set to true after it encounters the 400/500 from the back-end. In my reading of it the subsequent request with the full query then behaves as if persisted queries aren't supported so the hash is not generated/submitted.

**Comment by fooman** [comment]
Apollo Server seems to unconditionally create the hash here
https://github.com/apollographql/apollo-server/blob/0aa0e4b20ef97576ce92733698a7842b61d8280e/packages/apollo-server-core/src/requestPipeline.ts#L224 but does have the hash check here https://github.com/apollographql/apollo-server/blob/0aa0e4b20ef97576ce92733698a7842b61d8280e/packages/apollo-server-core/src/requestPipeline.ts#L209 when both query and hash are given.

**Comment by danslo** [comment]
Thanks @fooman , just letting you know that I have not forgotten about this issue, just been really busy this week :)

Will reproduce locally ASAP and figure out what the hell is going on :)
